### PR TITLE
Fixing mgmt commands for Django version compatibility

### PR DESCRIPTION
**Pull request by grahamu**
Testing this proposed fix via CI.

#18

### CODE REVIEW

**Comment by grahamu** [comment]
As seen in https://travis-ci.org/pinax/pinax-invitations/builds/112465540, some tests fail when invoked with Django master branch. As late as Django 1.9.x, there was some compatibility code found here: https://github.com/django/django/blob/stable/1.9.x/django/core/management/base.py#L307.

In Django master this code no longer exists, presumably as part of planned deprecation: https://github.com/django/django/blob/master/django/core/management/base.py#L263.

This PR fixes the parsing of these command arguments by both Django 1.8.x and 1.9.x, but when Django 1.10 is released we will need an entirely different fix in order to maintain backwards compatibility with Django v1.7.x.

**Comment by paltman** [comment]
Not sure if it matters but we can drop 1.7 support

**Comment by grahamu** [comment]
Thanks for your note about dropping Django v1.7 support @paltman. It does make a big difference to the code. I will update accordingly and that will remove the problem with compatibility with upcoming v1.10.

Does that Django compatibility change apply to all pinax apps? I'm happy to update tox.ini for pinax-invitations and pinax-documents.

**Comment by ossanna16** [comment]
@paltman Can this be merged?

**Pull request merged**
